### ISSUE TITLE
Error after running frontend

### ISSUE THREAD

**Issue by ashkan84f** [Bottelet/ticket-conductor#14]

**Comment by ashkan84f** [comment]
Hi,
First of all thank for what you have done. 
I am very new to nodejs, so I did trial and error to install it, and finally could install. lol.
Now the backend is running correctly, because there is no error, and I can open localhost:8000 without issue. But when I run the frontend, and try to refresh localhost:8000, I am getting the following error. I am sure the issue is because of my lack of knowledge, but it would be appreciated if you can take a look at the error. Thanks in advance.


webpack-dev-server 
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /dist/
✖ ｢wdm｣: Hash: 71e58de70fda8577927a
Version: webpack 4.25.1
Time: 9815ms
Built at: 2018-11-13 01:13:06
 1 asset
Entrypoint main = build.js
 [6] ./src/router/index.js 1.75 KiB {0} [built]
[12] multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js 40 bytes {0} [built]
[13] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {0} [built]
[14] (webpack)/node_modules/url/url.js 22.8 KiB {0} [built]
[21] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {0} [built]
[23] (webpack)-dev-server/node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[24] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[26] (webpack)-dev-server/client/overlay.js 3.58 KiB {0} [built]
[31] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[33] (webpack)/hot/emitter.js 75 bytes {0} [built]
[35] ./src/main.js 2.08 KiB {0} [built]
[36] ./node_modules/vue/dist/vue.js 283 KiB {0} [built]
[38] ./node_modules/vue-router/dist/vue-router.esm.js 64.1 KiB {0} [built]
[39] ./node_modules/vuetify/dist/vuetify.js 308 KiB {0} [built]
[40] ./src/app.vue 261 bytes {0} [built] [failed] [1 error]
    + 57 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/components/user/profile.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 11:15-56
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/layout/statistics.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 15:18-64
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/user/user.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 35:12-50
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/app.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/main.js 15:11-31
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/ticket/showTicket.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 23:18-64
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/consumer/showConsumer.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 27:20-70
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/ticket/ticket.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 19:14-56
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/consumer/consumer.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 31:16-62
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js

ERROR in ./src/components/group/group.vue
Module build failed (from ./node_modules/vue-loader/index.js):
TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/ashkan/Desktop/prj/ticket-conductor-frontend/node_modules/vue-loader/lib/loader.js:59:78)
 @ ./src/router/index.js 39:13-53
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js
ℹ ｢wdm｣: Failed to compile.

**Comment by Bottelet** [comment]
@arashk72 Did you do npm install or yarn install?

**Comment by ashkan84f** [comment]
@Bottelet npm.
